import type { Marker, PlayerState } from "./api";

export const mockPlayers: PlayerState[] = [
  {
    id: "mock-wing",
    name: "Wing",
    world: "world",
    dimension: "Overworld",
    x: 18,
    y: 72,
    z: -22,
    yaw: 120,
    pitch: 0,
    updatedAt: Date.now(),
  },
  {
    id: "mock-alex",
    name: "Alex",
    world: "world",
    dimension: "Overworld",
    x: -64,
    y: 68,
    z: 48,
    yaw: 260,
    pitch: 0,
    updatedAt: Date.now(),
  },
  {
    id: "mock-nether",
    name: "Builder",
    world: "world",
    dimension: "Nether",
    x: 112,
    y: 42,
    z: -80,
    yaw: 40,
    pitch: 0,
    updatedAt: Date.now(),
  },
];

export const mockMarkers: Marker[] = [
  {
    id: "spawn",
    world: "world",
    dimension: "Overworld",
    x: 0,
    y: 64,
    z: 0,
    title: "主城出生点",
    description: "公告牌、传送入口和公共仓库。",
    createdBy: "Wing",
    createdAt: Date.now() - 86400000,
    updatedAt: Date.now() - 3600000,
  },
  {
    id: "iron-farm",
    world: "world",
    dimension: "Overworld",
    x: -128,
    y: 68,
    z: 96,
    title: "铁厂",
    description: "不要移动村民和床。",
    createdBy: "Admin",
    createdAt: Date.now() - 7200000,
    updatedAt: Date.now() - 7200000,
  },
  {
    id: "nether-hub",
    world: "world",
    dimension: "Nether",
    x: 16,
    y: 58,
    z: -16,
    title: "下界交通站",
    description: "四向冰道入口。",
    createdBy: "Wing",
    createdAt: Date.now() - 6200000,
    updatedAt: Date.now() - 6200000,
  },
];
